# Generated by Django 3.1.1 on 2020-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='admin', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
